### ISSUE TITLE
question on django auth

### ISSUE THREAD

**Issue by rogeryen** [doableware/djongo#280]
Hello, this seems like a dumb question but I am not sure if djongo would work with django auth out of the box and what the best method to make it work. 

I have an existing mongodb from django-nonrel (really old django 1.6) integration that I am trying to migrate (or trying to prove that it can work) to use djongo. 

The first thing I ran into was `Cannot force an update in save() with no primary key.` and this is because I am using existing data in `auth_user` and there is no `id` but `_id`. I realized I had to override the primary key with _id but it looked like the only way to do it was creating a custom User extending `AbstractUser` with `_id` and change the `AUTH_USER_MODEL`. 

Next I noticed it was reading from a different collection because the AUTH_USER_MODEL is no longer `auth.User` so I had to override `db_table` on my custom User model. These steps got auth working for me but it seems like a lot of unorthodox workarounds so I wasn't sure if the steps I took were expected or if there's a better way?

Thanks!

**Comment by namndt** [comment]
I face same issue
