### ISSUE TITLE
Not sure what this was about

### ISSUE THREAD

**Issue by gkmk** [doableware/djongo#506]
Closing

**Comment by Hyeonproject** [comment]
So did I.

document say 'Features under development at DjongoNxt are not a part of the standard Djongo package. Visit the support page for more information.' ...

Ah.

**Comment by ronpetit** [comment]
It is pretty easy to just shout a lot of insults and curses, But that picture tells nothing.

I just added ID to one admin model and worked out of the box, so you might be doing something wrong, but nobody will help you with such attitude and without giving more information about how you set up everything.

<img width="1708" alt="Screen Shot 2020-12-09 at 23 27 22" src="https://user-images.githubusercontent.com/5855265/101713281-1fdc1100-3a76-11eb-9cd5-a34121ca381b.png">

**Comment by iacobfred** [comment]
Can't this issue be closed?

**Comment by mukundshah** [comment]
Yeah AutoID, does work out of the box, but only when there is one app with only one model. As soon as I introduce other models and apps, it gets messed up. So can you help me with this?

> It is pretty easy to just shout a lot of insults and curses, But that picture tells nothing.
> 
> I just added ID to one admin model and worked out of the box, so you might be doing something wrong, but nobody will help you with such attitude and without giving more information about how you set up everything.
> 
> <img alt="Screen Shot 2020-12-09 at 23 27 22" width="1708" src="https://user-images.githubusercontent.com/5855265/101713281-1fdc1100-3a76-11eb-9cd5-a34121ca381b.png">

**Comment by rudolfce** [comment]
@mukundshah Considering how this started, I don't think this is the best issue to look for help. Either find a duplicate one (with a more sensible title and description) or open new one.
